base:
  is_R50: 0
  is_SAMVIT: 1
  dataset_name: fgadr
  gpu_id: '4'
  original_checkpoint: 'lvm-med-vit' 
  best_valid_model_checkpoint: './working_dir/checkpoint/'
  frozen_eval: 0
  model: 'fcns'
  test_mode: 'best_valid'
  valid_rate: 0.2
  
train:
  train_batch_size: 12
  valid_batch_size: 1
  test_batch_size: 1
  learning_rate: 0.0001
  num_epochs: 30
  linear_eval: 0
  solver: 'adam'

dataloader:
  data_path: './dataset_demo/FGADR'
  