base:
  is_2D: 1
  is_3D: 0
  is_R50: 1
  is_SAMVIT: 0
  dataset_name: kvasir
  gpu_id: '1'
  original_checkpoint: 'lvm-med-resnet' # Original checkpoint from segment-anything project
  best_valid_model_checkpoint: './working_dir/checkpoint/Kvasir_R50'
  image_shape: 224

train:
  train_batch_size: 64
  valid_batch_size: 1
  test_batch_size: 1
  optimizer: 'adam'
  learning_rate: 0.001
  num_epochs: 35
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0
  scheduler: 0

dataloader:
  train_dir_img: './dataset_demo/Kvasir/train'
  train_dir_mask: './dataset_demo/Kvasir/train_labels'
  valid_dir_img: './dataset_demo/Kvasir/valid'
  valid_dir_mask: './dataset_demo/Kvasir/valid_labels'
  test_dir_img: './dataset_demo/Kvasir/test'
  test_dir_mask: './dataset_demo/Kvasir/test_labels'
  have_label: './dataset_demo/Kvasir/have_label.txt'
  non_label: './dataset_demo/Kvasir/non_label.txt'