base:
  is_2D: 0
  is_3D: 1
  is_R50: 1
  is_SAMVIT: 0
  dataset_name: las_ct
  gpu_id: '2'
  original_checkpoint: 'lvm-med-resnet' # Original checkpoint from segment-anything project
  best_valid_model_checkpoint: './working_dir/checkpoint/MMWHS_CT_R50'
  image_shape: 224

train:
  train_batch_size: 64
  valid_batch_size: 1
  test_batch_size: 1
  optimizer: 'adam'
  learning_rate: 0.001
  num_epochs: 20
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0
  scheduler: 1

dataloader:
  train_dir_img: './dataset_demo/MMWHS_CT_Heart/train'
  train_dir_mask: './dataset_demo/MMWHS_CT_Heart/train_labels'
  valid_dir_img: './dataset_demo/MMWHS_CT_Heart/valid'
  valid_dir_mask: './dataset_demo/MMWHS_CT_Heart/valid_labels'
  test_dir_img: './dataset_demo/MMWHS_CT_Heart/test'
  test_dir_mask: './dataset_demo/MMWHS_CT_Heart/test_labels'
  have_label: './dataset_demo/MMWHS_CT_Heart/have_label.txt'
  non_label: './dataset_demo/MMWHS_CT_Heart/non_label.txt'